'use strict';

const RN = require("react-native");

exports.activityIndicatorClass        = RN.ActivityIndicator;
exports.buttonClass                   = RN.Button;
exports.datePickerIOSClass            = RN.DatePickerIOS;
exports.drawerLayoutAndroidClass      = RN.DrawerLayoutAndroid;
exports.flatListClass                 = RN.FlatList;
exports.imageClass                    = RN.Image;
exports.inputAccessoryViewClass       = RN.InputAccessoryView
exports.imageBackgroundClass          = RN.ImageBackground
exports.keyboardAvoidingViewClass     = RN.KeyboardAvoidingView;
exports.listViewClass                 = RN.ListView;
exports.mapViewClass                  = RN.MapView;
exports.maskedViewIOSClass            = RN.MaskedViewIOS;
exports.modalClass                    = RN.Modal;
exports.navigatorIOSClass             = RN.NavigatorIOS;
exports.pickerClass                   = RN.Picker;
exports.pickerIOSClass                = RN.PickerIOS;
exports.pickerItemClass               = RN.Picker.Item;
exports.progressBarAndroidClass       = RN.ProgressBarAndroid;
exports.progressViewIOSClass          = RN.ProgressViewIOS;
exports.refreshControlClass           = RN.RefreshControl;
exports.safeAreaViewClass             = RN.SafeAreaView;
exports.scrollViewClass               = RN.ScrollView;
exports.sectionListClass              = RN.ScrollView;
exports.segmentedControlIOSClass      = RN.SegmentedControlIOS;
exports.sliderClass                   = RN.Slider;
exports.statusBarClass                = RN.StatusBar;
exports.snapshotViewIOSClass          = RN.SnapshotViewIOS;
exports.switchClass                   = RN.Switch;
exports.tabBarIOSClass                = RN.TabBarIOS;
exports.tabBarIOSItemClass            = RN.TabBarIOS.Item;
exports.textClass                     = RN.Text;
exports.textInputClass                = RN.TextInput;
exports.toolbarAndroidClass           = RN.ToolbarAndroid;
exports.touchableHighlightClass       = RN.TouchableHighlight;
exports.touchableNativeFeedbackClass  = RN.TouchableNativeFeedback;
exports.touchableOpacityClass         = RN.TouchableOpacity;
exports.touchableWithoutFeedbackClass = RN.TouchableWithoutFeedback;
exports.viewClass                     = RN.View;
exports.viewPagerAndroidClass         = RN.ViewPagerAndroid;
exports.virtualizedListClass          = RN.VirtualizedList;
exports.webViewClass                  = RN.WebView;
